# Generated by Django 3.2.7 on 2021-09-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Рабочий',
                'verbose_name_plural': 'Рабочие',
            },
        ),
    ]
